version: "3.8"

services:
    php:
        container_name: slim_php
        build:
            context: ./docker/php
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www/tracking_activity
        depends_on:
            - db

    nginx:
        container_name: slim_nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/tracking_activity
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        container_name: slim_db
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tracking_activity
            MYSQL_USER: tracking_activity_user
            MYSQL_PASSWORD: tracking_activity_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql